### ISSUE TITLE
Question about #EXT-X-MAP:URI

### ISSUE THREAD

**Issue by aureliendrouet** [xavierlaffargue/m3u8parser-csharp#21]
Hello,
Thank you for your great work. I have question related to #EXT-X-MAP:URI.
I could not find the uri of the initialization segment for the playback of a fMP4 container after parsing the media playlist. Could you please let me know if I missed something or if it is just not implemented?
Usually, I get the uri from #EXT-X-MAP:URI.

**Comment by xavierlaffargue** [comment]
This field was not implemented, I'm just added it on 1.0.4

**Comment by xavierlaffargue** [comment]
Now is ok for you?

**Comment by aureliendrouet** [comment]
Thank you very much. This is great.
